<?php
$auto_reviews_ship = array(
    array("name" => "Dávid H.", "text" => "Nem kellett sokat várnom, a kiszállítás professzionálisan történt."),
    array("name" => "Viktor M.", "text" => "A szállítás rendkívül gyors volt, minden információt megkaptam e-mailben és SMS-ben. Külön tetszett, hogy a futár érkezés előtt felhívott. Olyan érzésem volt, mintha minden a vásárló igényeihez lett volna igazítva."),
    array("name" => "István P.", "text" => "Minden időben megérkezett, a futár nagyon udvarias volt."),
    array("name" => "Miklós V.", "text" => "A csomagolás valóban minőségi, látszik a gondosság."),
    array("name" => "Máté K.", "text" => "A csomag sértetlenül és kiválóan becsomagolva érkezett. Minden megfelelően védve volt, így szállítás közben nem sérülhetett meg. Nagy dicséret a profizmusért."),
    array("name" => "Márk C.", "text" => "Hibátlan szállítási szolgáltatás."),
    array("name" => "Levente T.", "text" => "A futár udvarias és kedves volt, a kézbesítés pedig percre pontos. A csomag rendezett és sértetlen volt. Nagyon elégedett vagyok."),
    array("name" => "Zoltán T.", "text" => "Nagyon gyors szállítás és kiváló szervezés."),
    array("name" => "Bence S.", "text" => "Magas színvonalú szolgáltatás, minden világos volt."),
    array("name" => "Krisztián O.", "text" => "A csomagolás nagyon rendezett és biztonságos volt. Nem volt semmilyen sérülés, a szállítás a megbeszélt időben érkezett. Csak ajánlani tudom."),
    array("name" => "Zsolt J.", "text" => "Rendesen becsomagolva és biztonságosan kiszállítva."),
    array("name" => "Tamás R.", "text" => "A csomag a határidő előtt megérkezett."),
    array("name" => "János B.", "text" => "Minden hamarabb érkezett, mint vártam."),
    array("name" => "Dávid C.", "text" => "A szállítás pontos és gyors volt."),
    array("name" => "Zoltán U.", "text" => "A szállítás gyors volt, a csomagolás nagyon rendezett. Az ügyfélszolgálat munkaidőn kívül is elérhető volt. Ajánlom mindenkinek, aki gondtalan vásárlást szeretne."),
    array("name" => "Milán C.", "text" => "A csomagolás rendezett és minőségi."),
    array("name" => "Zoltán R.", "text" => "Az ügyfélszolgálat gyorsan válaszolt a szállítási idővel kapcsolatos kérdésemre. A csomag még a vártnál is hamarabb megérkezett. Mindenkinek ajánlom."),
    array("name" => "Sándor L.", "text" => "Nagyon egyszerű átvételi folyamat."),
    array("name" => "Tamás P.", "text" => "Gyors szállítás és egyszerű átvétel."),
    array("name" => "Dániel S.", "text" => "Nagyon jó szolgáltatás."),
    array("name" => "Szilárd H.", "text" => "A rendeléstől a kézbesítésig minden gördülékenyen ment. Mindig láttam a csomag státuszát, ami bizalmat adott. Nagyon minőségi szolgáltatás."),
    array("name" => "Péter V.", "text" => "Gyors szállítás."),
    array("name" => "Fülöp P.", "text" => "A csomag 2 napon belül megérkezett, ami nagyon meglepett. A csomagolás minőségi és rendezett volt. Biztosan újra rendelek."),
    array("name" => "Antal F.", "text" => "Minden gördülékenyen ment."),
    array("name" => "Márió D.", "text" => "A csomag a vártnál korábban érkezett."),
    array("name" => "Miklós J.", "text" => "A csomag sértetlenül érkezett."),
    array("name" => "Balázs I.", "text" => "A rendelés egyszerű volt, a szállítás még egyszerűbb. A követési információk világosak és naprakészek voltak. Kiváló szolgáltatás."),
    array("name" => "János K.", "text" => "Nincs kifogásom."),
    array("name" => "Dénes A.", "text" => "Online követtem a szállítást, minden tökéletesen működött. A csomag korábban érkezett és szépen volt becsomagolva. Minden információ időben elérhető volt."),
    array("name" => "Hunor M.", "text" => "A követési információkat azonnal megkaptam."),
    array("name" => "Boján R.", "text" => "Rendezett csomagolás, biztonságosan és sértetlenül érkezett."),
    array("name" => "András Z.", "text" => "A szállítás gyorsabb volt, mint ígérték."),
    array("name" => "Dávid G.", "text" => "A támogatás mindig elérhető volt."),
    array("name" => "Vladó F.", "text" => "Semmilyen problémám nem volt, minden gördülékenyen ment."),
    array("name" => "János Z.", "text" => "Az ügyfélszolgálat nagyon segítőkész volt és gyorsan válaszolt. A szállítás hamarabb érkezett, mint jelezték. Minden ajánlásom."),
    array("name" => "Ádám V.", "text" => "Nagyon elégedett vagyok."),
    array("name" => "Mihály B.", "text" => "Nagyon gyors szállítás."),
    array("name" => "József G.", "text" => "Rendesen becsomagolva és gyorsan kiszállítva."),
    array("name" => "Hunor D.", "text" => "A rendelés után minden nagyon gyorsan történt. A csomagot még aznap feladták, és már másnap megérkezett. Kiváló élmény."),
    array("name" => "Nándor T.", "text" => "Gyors rendelésfeldolgozás, kiváló."),
    array("name" => "Antal H.", "text" => "Ritkán látni ilyen professzionális szolgáltatást."),
    array("name" => "Gábor J.", "text" => "Hétfőn rendeltem, és már szerdán megérkezett a csomag. Az egész folyamat egyszerű és átlátható volt. Nagyon elégedett vagyok."),
    array("name" => "Miklós T.", "text" => "A szállítás gyorsabb volt, mint vártam. Minden szakaszról értesítést kaptam, ami bizalmat adott. Nagyon professzionális szolgáltatás."),
    array("name" => "Ádám F.", "text" => "A csomag hamarabb érkezett."),
    array("name" => "Márk Z.", "text" => "Az egész szállítási folyamat egyszerű volt."),
    array("name" => "János L.", "text" => "A rendelés után azonnal megkaptam a visszaigazolást és a csomagkövetési számot. A csomag sértetlenül és időben érkezett. A szolgáltatás ötös."),
    array("name" => "Krisztián N.", "text" => "A csomag tökéletes állapotban érkezett."),
    array("name" => "Marcell D.", "text" => "Csak dicsérni tudom – a rendeléstől a szállításig minden professzionálisan zajlott. A futár érkezés előtt felhívott, minden stresszmentes volt."),
    array("name" => "Máté R.", "text" => "A szállításkövetés kiválóan működött."),
    array("name" => "Péter L.", "text" => "A csomag rendezett csomagolásban és gyorsan érkezett."),
    array("name" => "Lukács F.", "text" => "Minden stresszmentesen zajlott – rendelés, visszaigazolás és szállítás. A csomag biztonságosan volt csomagolva és időben érkezett. Kiváló szolgáltatás."),
    array("name" => "Zoltán O.", "text" => "Minden gyorsan és gördülékenyen ment."),
    array("name" => "Márió E.", "text" => "Értékelem, hogy a futár udvarias volt és érkezés előtt telefonált. Nem kellett várakoznom, minden előre egyeztetve volt. Nagyon kellemes élmény."),
    array("name" => "Renátó K.", "text" => "A futár nagyon segítőkész volt."),
    array("name" => "Nikola B.", "text" => "Minden gördülékenyen és rendben zajlott."),
    array("name" => "Zoltán J.", "text" => "Dicséret az ügyfélszolgálatnak, gyorsan megoldották a kérdésemet."),
    array("name" => "Dávid L.", "text" => "A futár szállítás előtt telefonált, kiváló szervezés."),
    array("name" => "Dávid R.", "text" => "A futár kedves és profi volt. A csomag gond nélkül megérkezett. Nagyon pozitív tapasztalat."),
    array("name" => "István H.", "text" => "A futár segítőkész volt."),
    array("name" => "Viktor D.", "text" => "Gyors és rendezett szállítás."),
    array("name" => "Marcell K.", "text" => "Gyors és rendezett szállítás, sérülés nélkül."),
    array("name" => "Borisz I.", "text" => "Kiváló szállítási szolgáltatás."),
    array("name" => "Antal V.", "text" => "A csomag rendezetten és sérülésmentesen érkezett. A csomagolás erős és minőségi volt. Látszott a részletekre való odafigyelés."),
    array("name" => "István P.", "text" => "A futár a kézbesítés előtt felvette velem a kapcsolatot."),
    array("name" => "János J.", "text" => "Rendezett csomagolás, minden dicséretet megérdemel."),
    array("name" => "Damján E.", "text" => "Minden dicséret a gyorsaságért és pontosságért."),
    array("name" => "Dávid O.", "text" => "Minden pontosan úgy történt, ahogy meg volt adva."),
    array("name" => "Miklós H.", "text" => "Minden rendben és pontosan zajlott."),
    array("name" => "Balázs P.", "text" => "Minden dicséret."),
    array("name" => "Sven K.", "text" => "Minden kiváló volt."),
    array("name" => "Gábor F.", "text" => "A futár pontos és udvarias volt."),
    array("name" => "Tamás Z.", "text" => "Minden kiváló volt."),
    array("name" => "Márió J.", "text" => "Nem kellett sokat várnom."),
    array("name" => "Szabolcs J.", "text" => "A rendelés és szállítás teljes folyamata kellemes volt."),
    array("name" => "Máté C.", "text" => "Szuper szállítás."),
    array("name" => "Krisztián E.", "text" => "Rendezett szállítás."),
    array("name" => "János M.", "text" => "Minden átlátható és világos volt."),
    array("name" => "Lukács B.", "text" => "Minden információ elérhető volt."),
    array("name" => "József D.", "text" => "A szállítással kapcsolatos információk egyértelműek voltak."),
    array("name" => "Nándor B.", "text" => "Erős és biztonságos csomagolás, minden dicséret."),
    array("name" => "Miklós R.", "text" => "Gyorsan megérkezett."),
    array("name" => "Sándor D.", "text" => "A futár nagyon korrekt volt."),
    array("name" => "Levente M.", "text" => "Minden rendben és időben megérkezett."),
    array("name" => "Zoltán M.", "text" => "A csomag időben érkezett."),
    array("name" => "Krisztián V.", "text" => "Minőségi csomagolás, sértetlen csomag."),
    array("name" => "Lóránt N.", "text" => "Minden dicséret a szolgáltatásért."),
    array("name" => "Ádám K.", "text" => "A futár nagyon profi volt."),
    array("name" => "János T.", "text" => "Nagyon minőségi csomagolás."),
    array("name" => "Antal G.", "text" => "Erős csomagolás."),
    array("name" => "Marin G.", "text" => "Kiváló kommunikáció az ügyfélszolgálattal."),
    array("name" => "Dávid O.", "text" => "A szállítás rendkívül gyors volt."),
    array("name" => "Róbert E.", "text" => "Rendezett és erős csomagolás."),
    array("name" => "Fülöp M.", "text" => "Minden egyszerűen és komplikációk nélkül zajlott."),
    array("name" => "Antal I.", "text" => "A rendelés után azonnal megkaptam az összes követési adatot. A szállítás pontos és rendezett volt. Kiváló szervezés."),
    array("name" => "Márk P.", "text" => "Gyors szállítás, minden rendezett és jól becsomagolt."),
    array("name" => "Zsolt K.", "text" => "A teljes szállítási folyamat nagyon átlátható volt. Minden szakaszról értesítést kaptam. Stresszmentes és kiválóan működik."),
    array("name" => "Szergej G.", "text" => "Kiváló szolgáltatás, a futár nagyon profi volt."),
    array("name" => "Brúnó Z.", "text" => "Minden pontosan időben érkezett."),
    array("name" => "Szabolcs P.", "text" => "A szállítás minden része gördülékenyen zajlott. A futár udvarias és pontos volt, a csomag pedig rendezett. Nagyon elégedett vagyok."),
    array("name" => "Lukács J.", "text" => "Gyors szállítás, kedves futár és rendezett csomag."),
    array("name" => "Miklós S.", "text" => "A futár nagyon kedves volt."),
    array("name" => "Antal K.", "text" => "A szállítás minden fázisa jól kommunikált volt. A csomag korábban érkezett és jól be volt csomagolva. Nagyon pozitív élmény."),
    array("name" => "Dávid N.", "text" => "A támogatás hétvégén is elérhető volt, minden dicséret."),
    array("name" => "Fülöp K.", "text" => "A csomagkövetés tökéletesen működött."),
    array("name" => "Lukács C.", "text" => "Minden világos és rendezett volt, késés nélkül érkezett."),
    array("name" => "Károly P.", "text" => "Nagyon egyszerű átvétel."),
    array("name" => "Viktor C.", "text" => "Gyors és megbízható szállítás."),
    array("name" => "Dávid V.", "text" => "Minden probléma nélkül zajlott."),
    array("name" => "Antal I.", "text" => "A szállítás hibátlanul történt. A futár nagyon kedves volt és érkezés előtt telefonált. Dicséret az egész csapatnak."),
    array("name" => "Lóránt C.", "text" => "Minden késés nélkül megérkezett."),
    array("name" => "Róbert N.", "text" => "A támogatás mindenről tájékoztatott."),
    array("name" => "Zoltán E.", "text" => "Általában szkeptikus vagyok a véleményekkel kapcsolatban, de itt minden igaz volt."),
    array("name" => "Szilárd T.", "text" => "Semmilyen problémám nem volt."),
    array("name" => "Márió L.", "text" => "A csomag sértetlenül és rendezett állapotban érkezett."),
    array("name" => "Andor P.", "text" => "Minden gyorsan és egyszerűen zajlott. Időben érkezett, problémamentesen. Határozottan ajánlom."),
    array("name" => "Lóránt N.", "text" => "Minden dicséret a szolgáltatásért."),
    array("name" => "Miklós K.", "text" => "Nagyon gyors szállítás, udvarias futár. A csomag kiváló állapotban érkezett. Ajánlom."),
    array("name" => "Tóni H.", "text" => "Nagyon egyszerű rendelési folyamat."),
    array("name" => "Vendel R.", "text" => "Nem kellett sokat várnom, minden gyorsan megérkezett."),
    array("name" => "Marcell L.", "text" => "Minden gyors és egyszerű volt. Rendezett csomag, gyors és biztonságos szállítás. Nagyon pozitív tapasztalat."),
    array("name" => "Miklós S.", "text" => "A futár nagyon kedves volt.")
);
?>