<?php
$auto_reviews_en = array(
    array("name" => "György P.", "text" => "A szín ugyanolyan marad még sok mosás után is."),
    array("name" => "Miklós K.", "text" => "A Noriks póló valóban meglepett. Az anyag puha a bőrön, és a fazon követi a testet anélkül, hogy szorítana. Még egész nap viselés után is friss marad."),
    array("name" => "Dániel B.", "text" => "Modern és luxus kinézetű, pedig az ára nagyon megfizethető."),
    array("name" => "Tamás M.", "text" => "Minden nap viselem."),
    array("name" => "Sándor L.", "text" => "Eleinte nem voltam biztos benne, de felülmúlta a várakozásaimat. Veszek még."),
    array("name" => "Balázs I.", "text" => "Minimalista dizájn, mindenhez passzol."),
    array("name" => "István S.", "text" => "Tíz mosás után is olyan, mint új."),
    array("name" => "Mihály H.", "text" => "Nem látszik rajta az izzadság."),
    array("name" => "Péter R.", "text" => "Sovány és teltebb férfiaknak is tökéletes."),
    array("name" => "Attila P.", "text" => "A Noriks lett a mindennapi standardom. Puha, de tartós, megtartja a formáját. A méret megfelel a táblázatnak."),
    array("name" => "Márton K.", "text" => "Az anyag könnyű, de nem átlátszó."),
    array("name" => "Illés Z.", "text" => "Nagyon kényelmes póló. Már rendeltem is még. Szinte mindenhez passzol."),
    array("name" => "János I.", "text" => "Minden színhez illik."),
    array("name" => "Konstantin L.", "text" => "Elég hosszú ahhoz, hogy a nadrágban maradjon."),
    array("name" => "Péter H.", "text" => "Az anyag nem irritálja a bőrt még izzadás esetén sem."),
    array("name" => "Szilveszter T.", "text" => "Sporthoz és városban is."),
    array("name" => "Antal G.", "text" => "Puha, de strapabíró anyag."),
    array("name" => "Krisztián T.", "text" => "A minőség már első pillantásra látszik."),
    array("name" => "László K.", "text" => "Egyszerű, de modern."),
    array("name" => "Dénes P.", "text" => "Többet kaptam, mint amire számítottam."),
    array("name" => "Mihály U.", "text" => "Utazáson viseltem – még órák után sem gyűrődött a bőröndben."),
    array("name" => "György R.", "text" => "Szuper könnyű és kényelmes."),
    array("name" => "Tivadar L.", "text" => "Zakóval és melegítővel is viselem."),
    array("name" => "Miklós O.", "text" => "Tartós szín."),
    array("name" => "Tamás E.", "text" => "Már öt darabom van."),
    array("name" => "Alex T.", "text" => "Kiváló megjelenés és funkcionalitás."),
    array("name" => "Márton M.", "text" => "Prémium érzés tapintásra."),
    array("name" => "Róbert L.", "text" => "Férfias és elegáns."),
    array("name" => "Antal F.", "text" => "Majdnem minden második nap viselem – mindig rotációban van."),
    array("name" => "Miklós T.", "text" => "Puha, mint a pamut, de tartósabb."),
    array("name" => "Ádám M.", "text" => "Az anyag puha, de nem nyúlik még sok mosás után sem."),
    array("name" => "Fülöp P.", "text" => "A Noriks meggyőzött már az első viseléskor. Légáteresztő és nem tapad a bőrre."),
    array("name" => "Balázs L.", "text" => "Tökéletes ujjhossz."),
    array("name" => "György F.", "text" => "Régen kerestem ilyen modellt. Köszönöm!"),
    array("name" => "Krisztián B.", "text" => "Nagyon tartós — sok viselés után is olyan, mint új."),
    array("name" => "Attila T.", "text" => "Luxus tapintás."),
    array("name" => "Péter N.", "text" => "Dzsekivel is remekül néz ki."),
    array("name" => "Dániel V.", "text" => "Több mosás után sem kopott. Rendelek még."),
    array("name" => "Igor N.", "text" => "Egész nap viselés után sem gyűrődik."),
    array("name" => "Norbert U.", "text" => "A szín közelről még szebb."),
    array("name" => "Sven Z.", "text" => "Könnyen vasalható."),
    array("name" => "Zénó Z.", "text" => "Lelkes vagyok! Minden elvárásomnak megfelelt."),
    array("name" => "Adrián L.", "text" => "Minden nadrághoz passzol."),
    array("name" => "Antal F.", "text" => "Akkor is jól áll, ha méret között vagyok."),
    array("name" => "János K.", "text" => "Tökéletes méret."),
    array("name" => "Zsanett G.", "text" => "Ideális póló a modern férfi számára."),
    array("name" => "Domokos M.", "text" => "Klasszikus, egy kis stílussal."),
    array("name" => "Radim A.", "text" => "Sportos stílus elegáns befejezéssel."),
    array("name" => "Márton H.", "text" => "Irodába és szabadidőre."),
    array("name" => "Lukács I.", "text" => "Nem szorít a hónaljnál."),
    array("name" => "János M.", "text" => "A fazon magas embereknek is tökéletes."),
    array("name" => "István K.", "text" => "Megtaláltam az új kedvenc pólómat."),
    array("name" => "Bogdán S.", "text" => "Utazáshoz ideális – könnyű és könnyen szállítható."),
    array("name" => "Ferenc K.", "text" => "Állásinterjún viseltem – magabiztosnak éreztem magam."),
    array("name" => "Tamás H.", "text" => "Tökéletes hosszúság és fazon."),
    array("name" => "Miklós G.", "text" => "Munkához és sétához is viselem."),
    array("name" => "Vladimir G.", "text" => "Elegáns és kényelmes."),
    array("name" => "József L.", "text" => "Ideális egyensúly az elegancia és kényelem között."),
    array("name" => "Lukács T.", "text" => "Kiváló edzéshez és mindennapi használatra."),
    array("name" => "János I.", "text" => "Minőség az ár felett."),
    array("name" => "Leó Z.", "text" => "Megtartja a formáját és a színét."),
    array("name" => "Balázs E.", "text" => "Könnyen alakítható elegánsabb stílusra."),
    array("name" => "Martin T.", "text" => "Sok bókot kaptam."),
    array("name" => "Krisztián H.", "text" => "Nem fog szőrt."),
    array("name" => "Tibor V.", "text" => "Egész nap bírja."),
    array("name" => "Fülöp Z.", "text" => "Póló minden alkalomra."),
    array("name" => "Radek B.", "text" => "Egész nap kényelmes."),
    array("name" => "Mirek D.", "text" => "Minimalista és férfias dizájn."),
    array("name" => "Sasa O.", "text" => "Minden nap működik."),
    array("name" => "Róbert G.", "text" => "A legjobb online vásárlás."),
    array("name" => "Antal G.", "text" => "Minden reggel az első választásom."),
    array("name" => "Dávid L.", "text" => "Tökéletesen illeszkedik."),
    array("name" => "Krisztián B.", "text" => "A fazon valóban tökéletes — követi a vonalat anélkül, hogy szorítana."),
    array("name" => "Ádám O.", "text" => "Drágábbnak tűnik, mint amilyen."),
    array("name" => "Emil O.", "text" => "Luxus érzés."),
    array("name" => "Vencel U.", "text" => "Az anyag puha, de nem mutat kopást."),
    array("name" => "Tibor E.", "text" => "Az ujjak nem túl szűkek."),
    array("name" => "Péter M.", "text" => "Régen nem voltam ennyire elégedett egyszerű pólóval."),
    array("name" => "Domokos T.", "text" => "Sétához és esti programokhoz."),
    array("name" => "Brúnó K.", "text" => "Nem deformálódik."),
    array("name" => "Antal I.", "text" => "A szezon legkényelmesebb pólója."),
    array("name" => "Sziniša P.", "text" => "Gyorsan szárad."),
    array("name" => "Károly U.", "text" => "Casual stílus, ami tetszik."),
    array("name" => "Miklós Z.", "text" => "Kiváló ár-érték arány."),
    array("name" => "Fábián R.", "text" => "Alig gyűrődik — ideális."),
    array("name" => "Zlatko F.", "text" => "Végre modern póló a kényelem feláldozása nélkül."),
    array("name" => "Martin P.", "text" => "Feltétel nélkül ajánlom."),
    array("name" => "József X.", "text" => "Nyárra könnyű, rétegezéshez ideális."),
    array("name" => "Vladimir K.", "text" => "A kedvencem lett."),
    array("name" => "Erik I.", "text" => "Közelről még jobb, mint a fotókon."),
    array("name" => "Tamás S.", "text" => "Különleges megjelenés és érzés."),
    array("name" => "Károly Z.", "text" => "Pulóver alatt is ugyanolyan jó."),
    array("name" => "Zbynek N.", "text" => "Nem csúszik le a vállról."),
    array("name" => "János D.", "text" => "Kényelmes és professzionális."),
    array("name" => "Nino G.", "text" => "Egész nap friss marad."),
    array("name" => "Lukács M.", "text" => "Végre póló magasaknak is."),
    array("name" => "Boris T.", "text" => "Olyan kényelmes, mint a pizsama."),
    array("name" => "Fülöp K.", "text" => "Ideális hosszúság – nem jön ki a nadrágból."),
    array("name" => "Tamás I.", "text" => "Gyorsan szárad – utazáshoz ideális."),
    array("name" => "István M.", "text" => "Nemcsak jól néz ki, de jól is érzem magam benne."),
    array("name" => "Goran V.", "text" => "Ha minőséget keres – ez az."),
    array("name" => "Dávid I.", "text" => "Praktikus és modern."),
    array("name" => "Željko B.", "text" => "Minden outfit jobban néz ki."),
    array("name" => "Neven D.", "text" => "Ötös a barátnőmtől is."),
    array("name" => "Vedran G.", "text" => "Minden mosás után olyan, mint új."),
    array("name" => "János Z.", "text" => "A mindennapi outfitem része."),
    array("name" => "Krisztián D.", "text" => "Tökéletes egyensúly sport és elegancia között."),
    array("name" => "Mihály R.", "text" => "Megtartja a formáját és színét."),
    array("name" => "Máté V.", "text" => "Minden irányban tökéletesen illeszkedik."),
    array("name" => "Fülöp F.", "text" => "Mosás után sem változik a formája."),
    array("name" => "Ádám K.", "text" => "A szín sok ciklus után is tartós."),
    array("name" => "Krisztián P.", "text" => "A fazon követi a testet kényelmetlenség nélkül."),
    array("name" => "Balázs K.", "text" => "Teltebb alakoknak is passzol."),
    array("name" => "Tamás G.", "text" => "Sport után is tartós."),
    array("name" => "András N.", "text" => "Nehéz napokon is légáteresztő."),
    array("name" => "Antal K.", "text" => "Az anyag valóban minőségi érzést kelt."),
    array("name" => "Sasa R.", "text" => "12 óra munka után is bírta."),
    array("name" => "János N.", "text" => "Évek óta kerestem ilyen pólót."),
    array("name" => "Domokos R.", "text" => "Mindenhez passzol."),
    array("name" => "Lukács O.", "text" => "Kiváló alternatíva az inghez."),
    array("name" => "Emil T.", "text" => "Ideális megoldás minden napra."),
    array("name" => "Róbert N.", "text" => "Egy hónap mosás után is megtartja a minőséget."),
    array("name" => "Martin K.", "text" => "Egész nap viselés után sem kellemetlen."),
    array("name" => "Krisztián I.", "text" => "Munkához és szabadidőre."),
    array("name" => "József E.", "text" => "Tökéletesen illeszkedik."),
    array("name" => "Željko F.", "text" => "Ismételt használat után is olyan, mint új."),
    array("name" => "Dávid O.", "text" => "Minden testhelyzetben kényelmes."),
    array("name" => "Lukács B.", "text" => "Mindennap viselem."),
    array("name" => "Károly D.", "text" => "Olyan, mintha méretre szabták volna."),
    array("name" => "Sziniša G.", "text" => "Izzadás esetén is kiváló."),
    array("name" => "Branimir B.", "text" => "Mosás után nem nyúlik."),
    array("name" => "Damján S.", "text" => "Rétegezéshez ideális."),
    array("name" => "Antal V.", "text" => "Egész nap friss."),
    array("name" => "Tóni L.", "text" => "Napon is kellemes."),
    array("name" => "Miklós L.", "text" => "Sok bókot kapok."),
    array("name" => "Boris M.", "text" => "Kiváló termék — meg kellett írnom az értékelést."),
    array("name" => "Marian K.", "text" => "Könnyű karbantartás, gyors száradás."),
    array("name" => "Goran S.", "text" => "A nyak körüli részletek nagyon minőségiek."),
    array("name" => "Brúnó G.", "text" => "Úgy tűnik, évekig bírja."),
    array("name" => "Vencel K.", "text" => "Hízelgő a sziluettnek és nem átlátszó."),
    array("name" => "Fülöp O.", "text" => "Kiváló ügyfélszolgálat."),
    array("name" => "Zénó D.", "text" => "Vettem egyet és rögtön rendeltem még hármat."),
    array("name" => "Tamás P.", "text" => "Egész nap kényelmes."),
    array("name" => "István P.", "text" => "Kellően rugalmas."),
    array("name" => "Mihály S.", "text" => "Minőségi kivitelezés."),
    array("name" => "Viktor I.", "text" => "Izzadás esetén sem tapad."),
    array("name" => "Antal R.", "text" => "Egyszerűen tökéletes."),
    array("name" => "Lukács R.", "text" => "A legkényelmesebb pólóm."),
    array("name" => "Miklós A.", "text" => "Télen pulóver alatt is kiváló."),
    array("name" => "Radek E.", "text" => "Az értékelések nem hazudtak."),
    array("name" => "András I.", "text" => "Kiváló befektetés."),
    array("name" => "Dávid H.", "text" => "Tökéletes fazon és kényelem."),
    array("name" => "Balázs P.", "text" => "Minden kiváló."),
    array("name" => "Miroslav Z.", "text" => "A fazonnak köszönhetően ápoltabbnak tűnök."),
    array("name" => "Fülöp B.", "text" => "A legjobb testhez igazodás."),
    array("name" => "Krisztián E.", "text" => "Kellemes a bőrön, nincs nyom."),
    array("name" => "Marin D.", "text" => "Nem fog port vagy szőrt."),
    array("name" => "János D.", "text" => "Ideális annak, aki kényelmet és stílust keres."),
    array("name" => "Károly N.", "text" => "Napon sem melegít."),
    array("name" => "Márton K.", "text" => "Modern, de nem túlzó."),
    array("name" => "Željko E.", "text" => "Minden megfelel a valóságnak."),
    array("name" => "Sziniša H.", "text" => "Tiszta és egyszerű megjelenés."),
    array("name" => "Damján B.", "text" => "Munkához és esti programhoz."),
    array("name" => "Borivoj I.", "text" => "Logók nélkül, csak stílus."),
    array("name" => "Dániel K.", "text" => "Működő minimalizmus."),
    array("name" => "Jakab P.", "text" => "Rendeltem még kettőt."),
    array("name" => "Leó F.", "text" => "Az enyhe fény elegánsan néz ki."),
    array("name" => "Gordon I.", "text" => "A fazon kiemeli a sziluettet."),
    array("name" => "Vencel R.", "text" => "Régen nem voltam ennyire elégedett."),
    array("name" => "Tibor V.", "text" => "Minden napra tökéletes."),
    array("name" => "Mihály K.", "text" => "Nagyon kellemes a bőrön."),
    array("name" => "Ondrej V.", "text" => "Stabil minőség minden héten."),
    array("name" => "Dávid K.", "text" => "Valóban megéri."),
    array("name" => "Tamás N.", "text" => "A szárítógépet is bírja."),
    array("name" => "Boris U.", "text" => "Több színben is megvan."),
    array("name" => "Ádám T.", "text" => "Wow hatás az első pillanattól."),
    array("name" => "István H.", "text" => "A gallér tökéletesen tart."),
    array("name" => "Domokos E.", "text" => "A legjobb póló, ami valaha volt."),
    array("name" => "Antal H.", "text" => "Pontosan ezt kerestem."),
    array("name" => "Fülöp L.", "text" => "Kiváló kivitelezés."),
    array("name" => "Krisztián T.", "text" => "Könnyű, de tartós."),
    array("name" => "Marian O.", "text" => "Szabadság érzése."),
    array("name" => "Péter B.", "text" => "Párásságban is kiváló."),
    array("name" => "Ferenc D.", "text" => "Több darabot vettem."),
    array("name" => "Miklós M.", "text" => "Rugalmas és kényelmes."),
    array("name" => "János R.", "text" => "Nyáron és télen is működik."),
    array("name" => "Márton F.", "text" => "Professzionálisan néz ki."),
    array("name" => "Željko K.", "text" => "Intenzív használat mellett is tartós."),
    array("name" => "Vladimir F.", "text" => "Sok mosás után is megtartja a formáját."),
    array("name" => "Antal I.", "text" => "Jobb, mint a drága márkák."),
    array("name" => "Lukács B.", "text" => "Egész nap stabil marad."),
    array("name" => "Miklós V.", "text" => "Hónapok után is olyan, mint új."),
    array("name" => "Krisztián N.", "text" => "Tökéletes anyagsűrűség."),
    array("name" => "Borivoj K.", "text" => "Az első pillanattól tökéletesen ült."),
    array("name" => "Zénó U.", "text" => "Tökéletes hosszúság és vállak."),
    array("name" => "Mihály S.", "text" => "Nagyon elégedett vagyok."),
    array("name" => "Goran I.", "text" => "Működő minimalizmus."),
    array("name" => "Krešimir U.", "text" => "Magabiztosnak érzem magam."),
    array("name" => "Vedran F.", "text" => "Tökéletes mindennapi póló."),
    array("name" => "Dávid O.", "text" => "Kellemes meglepetés."),
    array("name" => "Miklós H.", "text" => "A gallér szárítógép után is tart."),
    array("name" => "Tibor G.", "text" => "Biztosan veszek még."),
    array("name" => "Angelo M.", "text" => "A textúra kiváló."),
    array("name" => "Žarko T.", "text" => "Gyors szállítás."),
    array("name" => "Miklós I.", "text" => "Tökéletes a vállakon."),
    array("name" => "András P.", "text" => "Legjobb ár-érték arány."),
    array("name" => "Ádám I.", "text" => "Mintha méretre szabták volna."),
    array("name" => "Vladimir K.", "text" => "Gyors szállítás, tökéletes csomagolás."),
    array("name" => "Dávid I.", "text" => "Szombatra és vacsorához."),
    array("name" => "Károly M.", "text" => "Bőrirritáció nélkül."),
    array("name" => "Ferenc P.", "text" => "Egész nap után sincs szag."),
    array("name" => "Zoran L.", "text" => "Vizuálisan jobb sziluett."),
    array("name" => "Igor S.", "text" => "Könnyű rendelés."),
    array("name" => "Antal D.", "text" => "Veszek másik színt is."),
    array("name" => "András K.", "text" => "Jobban érzem magam benne."),
    array("name" => "Mihály N.", "text" => "Vasalás nélkül is jó."),
    array("name" => "Goran P.", "text" => "Puha varrások."),
    array("name" => "János G.", "text" => "Irodához ideális."),
    array("name" => "Leó K.", "text" => "A szín megegyezik a fotókkal."),
    array("name" => "Damján P.", "text" => "Drágábbnak tűnik."),
    array("name" => "Ervin S.", "text" => "Puha és stabil."),
    array("name" => "Vencel M.", "text" => "Gyakori használat mellett is tartós."),
    array("name" => "Miklós B.", "text" => "Az anyag taszítja a foltokat."),
    array("name" => "István O.", "text" => "Az XL tökéletesen illeszkedik."),
    array("name" => "Boris R.", "text" => "Tiszta vonalak."),
    array("name" => "Antal S.", "text" => "Edzőteremtől a kávézóig."),
    array("name" => "Mihály P.", "text" => "A szürke remekül néz ki."),
    array("name" => "Fülöp G.", "text" => "Utazásokon is kényelmes."),
    array("name" => "János U.", "text" => "Az ajánlásom."),
    array("name" => "Károly P.", "text" => "Ing alatt is megtartja a formáját."),
    array("name" => "Máté D.", "text" => "Erőfeszítés nélküli stílus."),
    array("name" => "Emil K.", "text" => "Teljes elégedettség.")
);
?>
