<?php
$auto_reviews_en = array(
    array("name" => "György M.", "text" => "A boxer színe sok mosás után is ugyanolyan marad, semmi nem fakul."),
    array("name" => "Miklós P.", "text" => "A Noriks boxer valóban meglepett. Az anyag puha, nem irritál és nem szorít ott, ahol nem kellene."),
    array("name" => "Dániel S.", "text" => "Valóban kényelmes boxer egész napra, szinte nem is érzem."),
    array("name" => "Tamás R.", "text" => "A gumis derékpánt stabil, de nem szorít. Nem hagy nyomot a bőrön."),
    array("name" => "János D.", "text" => "Légáteresztő és könnyű, ideális munkához és edzéshez."),
    array("name" => "Lukács M.", "text" => "A boxer megtartja a formáját többszöri mosás után is, sehol nem nyúlik."),
    array("name" => "Krisztián K.", "text" => "Az anyag puha a bőrön, nincsenek kellemetlen varrások."),
    array("name" => "Dávid V.", "text" => "Egész nap viselés után is minden a helyén marad."),
    array("name" => "Mihály L.", "text" => "A Noriks boxer már az első érintésnél minőséget sugároz."),
    array("name" => "Péter G.", "text" => "Hetekkel ezelőtt viselem, semmi csomósodás vagy nyúlás."),
    array("name" => "Antal B.", "text" => "Tökéletes illeszkedés – követi a testet, de nem szorít."),
    array("name" => "Fülöp I.", "text" => "A szár nem csúszik fel, ami hatalmas plusz számomra."),
    array("name" => "Miklós R.", "text" => "A Noriks boxer az első választásom a fiókban."),
    array("name" => "Máté S.", "text" => "Nincs kellemetlen izzadás, az anyag szépen szellőzik."),
    array("name" => "Domokos K.", "text" => "Úgy tűnik, sokáig bírja – a varrások stabilak és tiszták."),
    array("name" => "János H.", "text" => "Kiváló ár-érték arány, jobb, mint sok drágább márka."),
    array("name" => "Zénó P.", "text" => "Nem gyűrődik a nadrág alatt, minden egyenesen marad."),
    array("name" => "Branislav N.", "text" => "Tökéletesen illeszkedik, még ha két méret között is vagyok."),
    array("name" => "René T.", "text" => "A gumis pánt nem veszíti el rugalmasságát sok mosás után sem."),
    array("name" => "András M.", "text" => "Ideális munkához és edzéshez – más márkát már nem veszek."),
    array("name" => "Dávid K.", "text" => "Olyan, mint a pizsama, de modern kinézetű."),
    array("name" => "Leó V.", "text" => "Szép formát ad anélkül, hogy bő lenne."),
    array("name" => "Darko Z.", "text" => "Az anyag gyorsan szárad, utazáshoz ideális."),
    array("name" => "Vencel H.", "text" => "Nem szorít, még ha órákig ülök is az irodában."),
    array("name" => "Károly F.", "text" => "Nincsenek kemény címkék, minden gondosan kidolgozott."),
    array("name" => "Tibor K.", "text" => "Egész nap viselem, és este is kényelmes."),
    array("name" => "Boris V.", "text" => "Nem forog és nem csavarodik a farmer alatt."),
    array("name" => "Márton Cs.", "text" => "Az illeszkedés szépen követi a lábat gyűrődés nélkül."),
    array("name" => "István K.", "text" => "Vettem egyet és rögtön rendeltem még hármat."),
    array("name" => "Radek N.", "text" => "A szín még a feketéknél is megmarad sok mosás után."),
    array("name" => "Dániel L.", "text" => "Nincs szag még nehéz nap után sem."),
    array("name" => "Goran V.", "text" => "Kicserélték az összes régi boxeremet."),
    array("name" => "Željko R.", "text" => "Sehol nem szorít, de mégis jól tart."),
    array("name" => "Vedran M.", "text" => "Nyárra ideális, nem tapad a bőrre."),
    array("name" => "Siniša I.", "text" => "A varrások puhák, nincs súrlódás."),
    array("name" => "Vladimir N.", "text" => "Kellően stabil, mégis könnyű."),
    array("name" => "Nino E.", "text" => "Edzés közben is mindent a helyén tart."),
    array("name" => "Saša K.", "text" => "Végre olyan alsónemű, ami nem irritál."),
    array("name" => "Igor V.", "text" => "Szárítógép után sem ment össze."),
    array("name" => "Jánek T.", "text" => "Magas embereknek is tökéletesen illeszkedik."),
    array("name" => "Tvrtko G.", "text" => "Tökéletes illeszkedés a derékban és a combokon."),
    array("name" => "Boris R.", "text" => "Olyan kényelmes, hogy szinte nem is érzem."),
    array("name" => "Károly D.", "text" => "Munkához és edzéshez – mindenre jó."),
    array("name" => "Milán H.", "text" => "A gumi nem hagy nyomot a bőrön."),
    array("name" => "Zoran P.", "text" => "Kellemes tapintású, nincs szintetikus érzés."),
    array("name" => "Dušan K.", "text" => "Az első boxer, ami nem csúszik fel."),
    array("name" => "Ferenc M.", "text" => "Ideális arány – sem szűk, sem bő."),
    array("name" => "Miklós H.", "text" => "Nem kell igazítani napközben."),
    array("name" => "Žarko V.", "text" => "Hosszú autóutakra is kiváló."),
    array("name" => "Marin I.", "text" => "Egy hónap mosás után sem veszíti el a formáját."),
    array("name" => "Tonđa P.", "text" => "Öltöny alatt is jól ül."),
    array("name" => "Ondrej K.", "text" => "Azóta mást nem akarok viselni."),
    array("name" => "Lukács V.", "text" => "Puha, de nagyon tartós."),
    array("name" => "Károly Z.", "text" => "Hőségben sem irritál."),
    array("name" => "Ladislav L.", "text" => "A legkényelmesebb boxer, ami valaha volt."),
    array("name" => "Viktor P.", "text" => "Ideális hosszúság, nem vág be."),
    array("name" => "Damir G.", "text" => "Prémium márkának tűnik."),
    array("name" => "Ádám S.", "text" => "A varrásokat szinte nem is érzem."),
    array("name" => "Krisztián I.", "text" => "Nem csomósodik és nem fog szőrt."),
    array("name" => "Lukács F.", "text" => "Tökéletes boxer minden napra."),
    array("name" => "Márton R.", "text" => "Edzés után is mindent tart."),
    array("name" => "Antal K.", "text" => "Kellemes meglepetés – 10/10 kényelem."),
    array("name" => "János O.", "text" => "Sokat vettem és csak ezeket váltogatom."),
    array("name" => "István V.", "text" => "Szűk nadrág alatt sem csúszik fel."),
    array("name" => "Dávid L.", "text" => "Az anyag nem tartja a nedvességet."),
    array("name" => "Goran U.", "text" => "Kiváló azoknak, akik sokat ülnek a számítógépnél."),
    array("name" => "Mirek E.", "text" => "Hetek után is újnak tűnik."),
    array("name" => "Brúnó Cs.", "text" => "Egyszerű, tiszta, férfias."),
    array("name" => "Miklós K.", "text" => "Tökéletes egyensúly a kényelem és a támogatás között."),
    array("name" => "Vencel I.", "text" => "Sehol nem vág be."),
    array("name" => "Srečko P.", "text" => "Könnyű karbantartás és gyors száradás."),
    array("name" => "Leó M.", "text" => "A színek megfelelnek a fotóknak."),
    array("name" => "Damján D.", "text" => "Hőségben is kényelmes marad."),
    array("name" => "Dorian S.", "text" => "Vékony nadrág alatt sem látszik át."),
    array("name" => "Adrián K.", "text" => "A széles gumi nem hajtódik be."),
    array("name" => "René H.", "text" => "Jelentősen kényelmesebben érzem magam bennük."),
    array("name" => "Zlatko R.", "text" => "Teltebb alakokra is jól van tervezve."),
    array("name" => "Tamás E.", "text" => "Munkához és edzéshez egyaránt problémamentes."),
    array("name" => "Károly L.", "text" => "Nem kell állandóan igazítani."),
    array("name" => "Nenad K.", "text" => "Nagy elégedettség, veszek még."),
    array("name" => "Dragan V.", "text" => "Nem csúszik le, egész nap tart."),
    array("name" => "Slavomir T.", "text" => "Tökéletes anyagvastagság."),
    array("name" => "Alberto N.", "text" => "Utazáshoz is kiváló."),
    array("name" => "Zénó V.", "text" => "Mosás után sincs deformáció."),
    array("name" => "Ilia S.", "text" => "Nem szorít a lágyéknál – végre."),
    array("name" => "Márton L.", "text" => "Mozgás közben is nagyon kényelmes."),
    array("name" => "Lukács S.", "text" => "Oldalt nem vág be."),
    array("name" => "Željko K.", "text" => "Ez a boxer megérdemel egy értékelést."),
    array("name" => "Antal Z.", "text" => "Teljesen új kényelmi szint."),
    array("name" => "Vladimir R.", "text" => "Ha egyszer kipróbálod, mást nem akarsz."),
    array("name" => "Goran Cs.", "text" => "Gyors szállítás, csúcstermék."),
    array("name" => "Vilém S.", "text" => "Tökéletesen illeszkedik, nem csúszik fel."),
    array("name" => "Oleg T.", "text" => "Olyan puha, hogy alig érzem."),
    array("name" => "István I.", "text" => "Egész nap semmilyen kényelmetlenség."),
    array("name" => "Károly H.", "text" => "A gumi kiváló, nem hajtódik be."),
    array("name" => "Darin P.", "text" => "Mosás után is olyan, mint új."),
    array("name" => "Adrián V.", "text" => "Kiváló anyag, légáteresztő."),
    array("name" => "Leó M.", "text" => "Ideális hosszúság, semmi nem mozdul."),
    array("name" => "Ágoston I.", "text" => "Az első választásom."),
    array("name" => "Krisztián U.", "text" => "Edzés után sincs izzadás."),
    array("name" => "Dejan T.", "text" => "Felülmúlta a várakozásokat."),
    array("name" => "Juraj A.", "text" => "Puha, de stabil."),
    array("name" => "Darko S.", "text" => "Nem gyűrődik a nadrágba."),
    array("name" => "Benedek K.", "text" => "Végre boxer, ami nem szorít."),
    array("name" => "Lóránt P.", "text" => "Nagyon minőségi anyag."),
    array("name" => "Ignác R.", "text" => "Újra veszek."),
    array("name" => "Marin D.", "text" => "Nagyon kellemes a bőrön."),
    array("name" => "Miron V.", "text" => "Tökéletesen kidolgozott varrások."),
    array("name" => "René M.", "text" => "Irodához és edzéshez."),
    array("name" => "Tivadar Z.", "text" => "Mást már nem akarok viselni."),
    array("name" => "Branislav S.", "text" => "Stabil, de kényelmes gumi."),
    array("name" => "Bálint R.", "text" => "Nem tartja a nedvességet."),
    array("name" => "Patrik L.", "text" => "Órák viselés után is kényelmes."),
    array("name" => "Tamás U.", "text" => "Hőségben sem irritál."),
    array("name" => "Márton S.", "text" => "Nagyon minőségi kivitelezés."),
    array("name" => "Miklós D.", "text" => "Edzés közben is tart."),
    array("name" => "Vitus P.", "text" => "10 mosás után is olyan, mint új."),
    array("name" => "Zénó T.", "text" => "Boxer, aminek van értelme."),
    array("name" => "Lukács K.", "text" => "Nem irritálja a bőrt."),
    array("name" => "Ernő V.", "text" => "Minden napra ideális."),
    array("name" => "Román V.", "text" => "Tökéletes a testalkatához."),
    array("name" => "Márián G.", "text" => "Nyáron és télen is kiváló."),
    array("name" => "Kristóf H.", "text" => "Egy hónap után sem tűnik kopottnak."),
    array("name" => "Tibor A.", "text" => "Az illeszkedés tökéletesen passzol."),
    array("name" => "Fábián S.", "text" => "Hosszú utakon is kényelmes."),
    array("name" => "Damján K.", "text" => "A legjobb boxer, amit vettem."),
    array("name" => "Sebestyén M.", "text" => "Prémium anyagminőség."),
    array("name" => "Zoran U.", "text" => "Nem szorítja a combokat."),
    array("name" => "Károly V.", "text" => "Mindent a helyén tart."),
    array("name" => "Dávid P.", "text" => "Hosszú nap után sincs kényelmetlenség."),
    array("name" => "Tin L.", "text" => "Mindennapi használatra ideális."),
    array("name" => "Ota R.", "text" => "Egész nap nem csúszik fel."),
    array("name" => "Slavko I.", "text" => "Csúcskényelem."),
    array("name" => "Jánek S.", "text" => "Kiváló egyensúly a kényelem és támogatás között."),
    array("name" => "Máté V.", "text" => "Nincs csúszós érzés."),
    array("name" => "János P.", "text" => "Megtartja a formáját."),
    array("name" => "Julián D.", "text" => "Az anyag hihetetlenül puha."),
    array("name" => "Máté H.", "text" => "A gumi nem megy tönkre."),
    array("name" => "Vitus Cs.", "text" => "A minőség jobb, mint vártam."),
    array("name" => "Bonó K.", "text" => "Nem tudtam, hogy a boxer ilyen jó lehet."),
    array("name" => "Radek U.", "text" => "Kiváló szellőzés."),
    array("name" => "Ladislav F.", "text" => "Hosszú séta után sincs súrlódás."),
    array("name" => "Mihály T.", "text" => "Hőségben is kényelmes."),
    array("name" => "Vilém P.", "text" => "Ideális a testalkatához."),
    array("name" => "Ademir S.", "text" => "Az anyag kiválóan szellőzik."),
    array("name" => "Harun I.", "text" => "Nagyon könnyű és szellős."),
    array("name" => "Nóa M.", "text" => "Megtartja a színét, nem fakul."),
    array("name" => "Tamás Cs.", "text" => "Farmer alatt is kényelmes."),
    array("name" => "Bálint L.", "text" => "Nagyon kellemes érzés."),
    array("name" => "Dárió S.", "text" => "Valóban kiváló boxer."),
    array("name" => "Leó N.", "text" => "Minden nap viselem."),
    array("name" => "Vencel I.", "text" => "Nincs gyűrődés és csavarodás."),
    array("name" => "Dávid P.", "text" => "Többet kaptam, mint vártam."),
    array("name" => "Ferenc S.", "text" => "Biciklizéshez is kiváló."),
    array("name" => "Erik R.", "text" => "Határozottan ajánlom."),
    array("name" => "Szilvió M.", "text" => "Nem csomósodik."),
    array("name" => "Zlatán G.", "text" => "Nem csúszik felfelé."),
    array("name" => "Dalibor S.", "text" => "Érzékeny bőrre ideális."),
    array("name" => "Gorián P.", "text" => "A gumi nem hagy nyomot."),
    array("name" => "Bohumil T.", "text" => "Maximális kényelem."),
    array("name" => "Ádám F.", "text" => "Teljes game-changer."),
    array("name" => "István L.", "text" => "Gyorsan szárad."),
    array("name" => "Marek Z.", "text" => "Nadrág alatt nem gyűrődik."),
    array("name" => "Vladimir S.", "text" => "Egész nap után sincs szag."),
    array("name" => "Lukács R.", "text" => "Végre boxer, ami tart."),
    array("name" => "Fülöp U.", "text" => "Könnyű karbantartás."),
    array("name" => "Boris K.", "text" => "Puha és nagyon tartós."),
    array("name" => "János X.", "text" => "A legjobb ebben az árban."),
    array("name" => "Brúnó V.", "text" => "Valóban nem csúszik fel."),
    array("name" => "Ondrej K.", "text" => "Nagy elégedettség az anyaggal."),
    array("name" => "Šandi V.", "text" => "Nem irritálja a bőrt."),
    array("name" => "Kevin S.", "text" => "Mindennap viselem."),
    array("name" => "Mátyás P.", "text" => "Kiváló érzés viselés közben."),
    array("name" => "Martin V.", "text" => "Egy hónap után is olyan, mint új."),
    array("name" => "Oszkár L.", "text" => "Stabil, de rugalmas."),
    array("name" => "Dávid I.", "text" => "Edzés közben sem szorít."),
    array("name" => "Miklós U.", "text" => "Egyszerűen tökéletes."),
    array("name" => "Sven M.", "text" => "A gumi nem hajtódik be."),
    array("name" => "Róbert P.", "text" => "Az egyik legkényelmesebb boxer."),
    array("name" => "Károly V.", "text" => "Határozottan ajánlom."),
    array("name" => "Tamás S.", "text" => "Az anyag valóban szellőzik."),
    array("name" => "Radek K.", "text" => "Sportoláshoz is kiváló."),
    array("name" => "Dávid Z.", "text" => "Nincs panaszom."),
    array("name" => "Danilo F.", "text" => "Megéri minden forintját."),
    array("name" => "Mirek K.", "text" => "Minden nap viselem."),
    array("name" => "Sebestyén R.", "text" => "Hibátlan. Újra veszek.")
);
?>
